OsProgramadores/op-website-hugo

- config.toml
A palavra programação estava escrita como progamação na sessão de administradores do site.
Problema corrigido.
> Correcao de ortografia na sessao de administradores do site.

- config.toml
A palavra religião estava escrota como religão na sessão de administradores do site.
Bug corrigido.
> Resolvido problema de ortografia da palavra religiao.

- config.toml
- Linguagem temporariamente modificada pra en-us. É necessario
criar um arquivo de tradução antes de modificar a linguagem.
- "Artigos" modificado para "Blog". Por alguma razão, arquivos
markdown embaixo de content/artigos não produziam saída.
- Modificada a descrição default do site.
- "Features" desabilitadas (evita mensagem de erro na renderização)
> Acertos no arquivo de configuração.

- static/js/front.js
O default do testimonials.owl é de 4 cards, com overrides por tamanho de
browser. Tudo abaixo de 990 pixels deveria mostrar apenas 3 cards. Ao
mudar o default de 4 para 3, o browser continua mostrando 4 cards com
janelas de até ~1200 pixels. Como só temos 3 admins, foi modificado o
tamanho default para 3, e forçado o tamanho do "small browser" para 2560
pixels (tipico de monitores grandes formato 16:10).
> Centraliza os 3 cards dos "Administradores".

- layouts/partials/participantes.html
Map looks more like a standard mercator projection, showing up to the southern tip of South America and all of Australia in one page (Alaska somewhat broken into two, though).
> Better map visualization (zoom/positioning).

- content/instrucoes.md
Acerto de um Link em Instruções, faltava o link para o BOT na parte do iPhone
> Acerto de um Link em Instruções

- config.toml
- layouts/partials/links.html
Agora esta responsivo em dispositivos pequenos, como um iphone 5.
Antes a tabela com 3 colunas ficava quebrada.
Arrumei um erro na description dos podcasts.
> Melhorando responsividade para dispositivos xs

- .travis.yml
- This should reduce the "mail-on-green" spam.
> Only email errors on change of status.

- content/blog/grupos_telegram.md
Removido o grupo Pygrameiros da lista de grupos do Telegram. O grupo aparentemente não existe mais ou mudou de nome.
> Removido o grupo Pygrameiros da lista de grupos do Telegram.

- content/desafios/d01.md
- Não é necessário (ou desejável) ter os números reais. Colocando todos como "1." dá ao markdown a chance de numerar em ordem crescente.
- Adicionado um indent ao bloco "preformatado", pra evitar a quebra da numeração.
- Adicionadas instruções de como adicionar um remote apontando para o upstream.
> Conserto de numeração, instruções p/upstream.

- static/css/custom.css
- Elementos pre-formatados agora utilizam preto no azul claro ao invés do (horrível) vermelho no rosa.
- Modificada a fonte de `<code>` para usar "Courier New" em último caso (depois de "Monospace").
> Melhora visualização de código pre-formatado.

- content/blog/grupos_telegram.md
Alguns grupos foram retirados pois os links já não existem mais. E foi alterado um link de um grupo (AngularJS) que mudou seu id, conforme informa o link antigo.
> Atualiza a lista de grupos do Telegram.

- content/blog/grupos_telegram.md
- content/links.md
Adiciona os links do Telegram da postagem do blog à página Links. Também padroniza a ortografia de alguns termos por todo o documento.
>  Adiciona links do Telegram à links.md 

- content/regras.md
- No Telegram canais, grupos e usuários são identificados pelo @, não pelo #. Vírgula indevida.
- Crase.
- Porquês.
- Verbo ter concorda com o sujeito (aqueles/eles).
- A página inicial do Repl.it não é mais tão intuitiva para escolher uma linguagem se você não tiver uma conta, enviando o usuário direto para http://repl.it/languages o deixa numa posição mais fácil de acessar a função de IDE online. Embelezar alguns links.
- Crase. Português brasileiro.
> Spellcheck

- layouts/partials/recent_posts.html
This file was copied from the theme, with .Data.Pages changed to
.Site.RegularPages, which is a list of all regular pages on the entire
site (hugo 0.58+). For further details, see:
https://gohugo.io/variables/site/#site-variables-list
> Fix broken "recently articles" under hugo 0.58+

- data/links/telegram-grupos.yaml
- Remove o grupo JavaScript Brasil, que foi aparentemente abandonado.
- Renomeia o "Javascript Brasil 2" --> Javascript Brasil.
- Fixes #700
> Remove grupo JavaScript Brasil.

- .github/workflows/deploy.yaml
- Rebuild and push the website every 30m, in addition to doing it on
pushes. This guarantees that changes to op-desafios will be picked
eventually.
- Change rsync to use checksums, so that only files that effectively
changed will be copied.
> Push website every 30m, use checksums for rsync.

- PARTICIPANTES.md
O usuário @leobaianoBR vai começar a participar do desafio do grupo OsProgramdores e para isto é preciso ser adicionado na tabela de participantes.
- Adiciona o usuário @leobaianoBR a tabelade participantes do desafio.
> Inclusão de participante: @leobaianoBR.

- content/desafios/d03.md
Ao ler o texto do desafio 03 para fazê-lo, percebi uma aparente ambiguidade na frase abaixo:
> Observe que o número inicial e final devem ser incluídos nos resultados.
> Exemplo 1:
> Dado o número inicial 1 e número final 20, o resultado seria: 1, 2, 3, 4, 5, 6,
7, 8, 9, 11.
> Exemplo 2:
Dado o numero inicial 3000 e número final 3010, o resultado seria: 3003.
> Exemplo 3:
Dado o número inicial 101 e número final 121, o resultado seria: 101, 111, 121.
O exemplo 3 ajuda a remover a ambiguidade mas sem uma condição extra, sugerida nesse PR, o parágrafo inicial aparenta indicar que o número inicial e final devem sempre ser inseridos nos resultados, sendo palíndromos ou não.
Minha sugestão é alterar para (porção em negrito):
> Observe que o número inicial e final devem ser incluídos nos …
> Sugestão de frase para remover ambiguidade no texto do desafio 03

- layouts/_default/desafios.html
@mpinheir me pediu para opinar com alguns comentários sobre a página dos desafios. Iniciei a revisão pelas instruções que aparecem no site Os Programadores (https://osprogramadores.com/desafios/). O texto em si está claro (para mim) mas pode trazer alguma dificuldade para novatos, menos experientes com os termos técnicos.
Além disso, algumas informações extras podem ajudar a nortear, como por exemplo indicar as linguagens não suportadas pelo linter online.
Talvez seja interessante colocar um link para o repositório do linter online para incentivar contribuições, @mpinheir. Talvez até já exista mas eu ainda não vi.
1. **23b08e3** Remoção de um dos links na primeira instrução para os desafios
- Motivação: Os links levam ambos para o repositório dos desafios, com uma sutil diferença de um …
> Algumas sugestões para as instruções dos desafios

- content/blog/conceitos-essenciais-para-começar.md
Pequeno ajuste pois o sumário do artigo, na página principal do site, estava exbindo a palavra introdução. Não sei se é um bug do Hugo ou o que é mas removendo o # Introdução, resolve o problema.
> Corrige problema de exibição

- README.md
Este commit adiciona uma nota sobre a utilização do parâmetro ```--recursive``` e o seu pseudômino (alias) no README.md do repositório. 
Eu adicionei um link para a documentação, infelizmente não há tradução para o português desta página. A outra página sobre submódulos que foi traduzida é sobre o comando ```git submodules```, e ela não possui explicação sobre os submódulos em si como nesta página referenciada da documentação. 
Se acharem melhor, vocês podem remover ou substituir o link por um conteúdo em português. Aceito sugestões.
> adiciona nota ao parâmetro ```--recursive``` ao clonar um repositório

- content/desafios/d06.md
Apenas adicionei a descrição no desafio para os participantes enviarem apenas os arquivos com a solução no D6, acho desnecessário enviar o arquivo com as palavras juntos(os PR`s ficam com várias linhas a mais).
> Adicionar descrição para desafio 6.

- layouts/_default/desafio.html
Apenas adicionei um comentário para a galera checar o código no linter antes de enviar, muitos arquivos estão parando na actions devido a erros de formatação.
> Adicionar link para linter na seção de validações 
