readme.md

-Adicionado resultados do desafio via Telegram:
*Fazer um fork do projeto;
*Editar readme.md com nome, email, GitHub e enviar pull-request;

Atualizando readme.md com desafio

---

PARTICIPANTES.md
README.md

Adicionei instruções de clonagem do repo no ARQUIVO README.md
Criei o arquivo PARTICIPANTES.md

Adicionei instrucoes para o clone do repositorio do projeto.

---

.gitmodules

Primeiro passo. Várias outras alterações a serem feitas.

Tema trocado de elate para universal.

---

.gitignore
config.toml
content/blog/hacking.md
content/blog/qual_linguagem_usar.md

Algumas melhorias de ortografia e estilo.

Correções ortográficas e elegância

---

PARTICIPANTES.md

updating PARTICIPANTES.md

---

config.toml

Adicionado disqus

---

config.toml

@qrwteyrutiyoup verifica e aprova por favor se correto.

Ajuste no baseurl para baseurl = "https://osprogramadores.com/".

---

content/blog/grupos_telegram.md

Adicionei grupo sobre AngularJS a lista de grupos sobre programação.

Adicionado grupo sobre AngularJS a lista de grupos sobre programação

---

PARTICIPANTES.md

Concluindo o desafio #1 do site

---

PARTICIPANTES.md

Adicionado informações de Marcos Teruo Ouchi atendendo ao solicitado no exercício #1.

Concluído Exercício #1

---

PARTICIPANTES.md

- Victor Eduardo Santos Soares
Email: v_eduardo@live.com
GitHub: https://github.com/veduardo93

Inserção de dados:

---

.gitignore
PARTICIPANTES.md

Ajustes de formação no PARTICIPANTES.md e do .gitignore

Ajustada a formatação do arquivo PARTICIPANTES.md

---

config.toml
content/heatmap.md
layouts/partials/heatmap.html
layouts/partials/scripts.html

Inclusão do Menu HeatMap

---

PARTICIPANTES.md
README.md

Adicionei novo participante e corrigi uma palavra escrita errada no README.md

Add novo participante

---

PARTICIPANTES.md

Dados do participante Clederson

Dados do participante Clederson

---

layouts/partials/participantes.html

Tradução do menu e remoção de um deles!

Tradução do menu

---

PARTICIPANTES.md

Added participant Alexsandro Felix

Updated PARTICIPANTES.md

---

content/instrucoes.md

Colocar link para o BOT

---

PARTICIPANTES.md

Referente ao Desafio #1 do site OsProgramadores.com

Inclusao da participante Ligia Salzano

---

content/links.md

Coloquei tabelas para organizar os links, cada sessão dentro de uma aba diferente, e na aba de podcasts coloquei thumbnails.
Todos links que já estavam no site eu coloquei nessas tabelas, além de vários outros, uns que eu conhecia, outros que procurei na hora, principalmente os Podcasts, não conheço todos ainda, mas são todos de Tecnologia/TI/Programação.

Organização dos links

---

PARTICIPANTES.md

- Adição da minha linha (@mrcrch)
- Correção da linha da usuária @ligiasalzano

Adição de novo participante e correção de linha já existente

---

PARTICIPANTES.md

cout << "Hello World" << endl;

Add my name (Gabriel DS)

---

config.toml
content/blog/contribuindo.md

Adicionei a opção de Menu Colabore ao menu principal do site.
A opção leva o usuário até a página que explica como fazer uma contribuição para o site.

Adicionei a opção de Menu Colabore ao menu principal do site

---

content/desafios/d05.md

http://localhost:1313/

---

PARTICIPANTES.md

Desafio nº01 concluído. Novo participante adicionado: "Alex Almeida".

Novo participante: Alex Almeida

---

.travis.yml
travis/checkparticipantes.go

Added travis functionality to verify PARTICIPANTES.md file integrity.

Added travis functionality to verify PARTICIPANTES.md file integrity.

---

.travis.yml

Applied correction to checkparticipantes path on travis.yml file.

Applied correction to checkparticipantes path on travis.yml file.

---

.travis.yml

Updated travis.yml to force go build output to checkparticipantes.

Updated travis.yml to force go build output to checkparticipantes.

---

PARTICIPANTES.md

Before this change, the recommended order wast lastname/firstname, but this created a lot of confusion. Changed to first/last name (and to make the list comply with checkparticipantes.go)

Change ordering of names in PARTICIPANTES.md.

---

content/desafios/d05.md

In an attempt to make it more clear. We also define the expected output
for it.

Update challenge 05

---

.travis.yml

Added notification information to travis.yml.

Added notification information to travis.yml.

---

content/regras.md

- Adicionada front-matter.
- Acertos nos níveis de cabeçalho.
- Removido c9.io como uma alternativa de cloud IDE (agora pertence a Amazon/AWS, com indicações de ser pago.)

Melhorias do texto das regras.

---

PARTICIPANTES.md

Olá.
Como instruído, fiz as modificações.

Add new participant

---

PARTICIPANTES.md

Adicionando participante Luiz

---

PARTICIPANTES.md

Novo Participante Desafio #1

---

PARTICIPANTES.md
travis/checkparticipantes.go

* Simplified the main program.
* Now check for names out of sequence, invalid emails and invalid github URLs.
* Improved markdown header detection.
* Fixed PARTICIPANTES.md to be compliant with the new rules.

Improvements and bugfix for checkparticipantes.go

---

PARTICIPANTES.md

Adicionado participante Hemílio

adicionado hemilio em participantes.md

---

PARTICIPANTES.md
travis/checkparticipantes.go

- Disallows tabs in the file. Tabs were creating a big confusion with
the table.
- Check for blank names.
- Check for column misalignment on the table.

Added more checks to checkparticipantes.go.

---

layouts/_default/single.html
layouts/page/single.html
layouts/partials/scripts.html
static/css/custom.css
static/js/anchorforid.js

- Add automatic header links to single blog entries.
- This also include rules.
- TODO: Convert blog entries to use H2 levels (only H2 down is
automatically linked).

Add automatic header links.

---

PARTICIPANTES.md

Adicionei meu nome na lista de participantes, como parte da primeira etapa de desafios.

Adicionei meu nome  na lista de participantes

---

PARTICIPANTES.md

inserido o nome

---

content/blog/grupos_telegram.md

Adicionado o grupo TI no Canadá na lista de grupos do Telegram.

Adicionado o grupo TI no Canadá na lista de grupos do Telegram.

---

content/blog/grupos_telegram.md

Adicionados novos grupos a lista e alterado http para https.

Adicionados novos grupos a lista e alterado http para https.

---

content/blog/grupos_telegram.md

Adição de grupos a lista de grupos do Telegram.

Adição de grupos a lista de grupos do Telegram.

---

content/blog/grupos_telegram.md

Adicionados grupos a lista de grupos do Telegram.

Adicionados grupos a lista de grupos do Telegram.

---

PARTICIPANTES.md

Inserção dos meus dados na lista de participantes.

Desafio #1

---

PARTICIPANTES.md

Conforme manda o desafio, adicionado a minha informação e feito um pull request..

Desafio d01 

---

PARTICIPANTES.md

Adicionei os meus dados conforme descrito na página do grupo.

Adição de participante

---

PARTICIPANTES.md

Completando o 1º desafio do site.

Adicionando minhas informações ao arquivo PARTICIPANTES.md

---

config.toml

Adicionado link para "Um tour por Go" ao tab Cursos Gratuitos da sessão de Links do site.

Adicionado link para "Um tour por Go" ao tab Cursos Gratuitos.

---

config.toml

Adicionado link para a Linguagem Kotlin a sessão de Documentações.

Adicionado link para a Linguagem Kotlin a sessão de Documentações.

---

config.toml
content/faq.md
content/regras.md

- Removido o link [Home] no menubar (desnecessário)
- Menubar reordenado.
- Alguns tópicos dentro de regras movidos para a nova seção FAQ (que contém outras perguntas além das iniciais em Regras).

Adicionada uma FAQ do grupo ao site.

---

PARTICIPANTES.md

Adicionada participante Celina Uemura

---

PARTICIPANTES.md

por favor me adicione aos participantes

adicionado meu nome aos participantes

---

PARTICIPANTES.md

Adicao de participante

---

PARTICIPANTES.md

Completando o Desafio #1 do site OsProgramadores.

Adição do participante Fabricio967 (#37).

---

PARTICIPANTES.md

adicionado felipe ceglia, desafio 1

adicionado felipe ceglia

---

PARTICIPANTES.md

Esse PR visa adicionar o usuário `paulohpinheiro` à lista de participantes.

Adiciona paulohrpinheiro à lista de participantes

---

config.toml

Adicionei o link para minha pesquisa sobre ferramentas RAD, como se trata de um conjunto de ferramentas coloquei na sessão de ferramentas, talvez quando a pesauisa amadurecer mais possamos colocar em um lugar mais adequado e mostrar mais dados.

Adiciona link com pesquisa sobre ferramentas RAD.

---

PARTICIPANTES.md
config.toml

Mudanças: 
* Links para ebooks, ferramentas e uma empresa de cursos adicionados;
* Meus dados (email e usuário GitHub) atualizados;

Alguns links adicionados ao sites e dados alterados

---

PARTICIPANTES.md

Solicitando registro de participante.

adicionando participante.

---

PARTICIPANTES.md

Inclusão de Igor Tuag

---

content/desafios/d07.md

- Arquivos de teste são agora armazenados em osprogramadores.com/files.

Adicionado procedimento de teste no d07.

---

PARTICIPANTES.md

Diego Nonato

---

PARTICIPANTES.md

Adicionei meu nome, email, e conta github no arquivo participantes.md

adicionando meu nome

---

PARTICIPANTES.md

Adicionado os meus dados no arquivo PARTICIPANTES.md

Novo participante

---

PARTICIPANTES.md

modified:   PARTICIPANTES.md com minhas informações.

Adiciona @kernelkill aos participantes (#268)

---

content/desafios/d10.md

Please take a careful look at the text. Also, please review and approve, but
let me do the merge (since it needs to coordinate with other repos).

Added desafio-10 (Turing machine).

---

content/desafios/d11.md

Por favor, verifiquem se tudo parece OK e se é possível entender
o enunciado (com razoável clareza) :)

Added desafio-11 (primes in pi).

---

content/desafios/d01.md
content/desafios/d02.md
content/desafios/d03.md
content/desafios/d04.md
content/desafios/d05.md
content/desafios/d06.md
content/desafios/d07.md
content/desafios/d08.md
content/desafios/d09.md
content/desafios/d10.md
content/desafios/d11.md
layouts/_default/desafios.html
layouts/partials/head.html
static/css/custom.css

- Layout mais compacto para a página de desafios.
- Agora usa "description" nos desafios individual para evitar overrun.
- Layout com "cards" de tamanho fixo, ícone, dificuldade e pontuação.
- Font-awesome atualizada para versao 5.6.3 (ícones).

Novo layout para a página de desafios.

---

config.toml
layouts/partials/footer.html

Uma sugestão de mudança para tornar a variável "year" do copyright dinâmico.
https://geekthis.net/post/hugo-dynamic-copyright-year/

Ano atual do copyright dinâmico.

---

config.toml
layouts/_default/desafios.html
static/css/custom.css

- Cards are now smaller and cleaner.
- Fewer colors.
- Changed number of blog pages in a list to 12.

More cleanup on desafios (cards).

---

PARTICIPANTES.md

Inclusão do meu nome no projeto

Adicionado Novo Usuário

---

PARTICIPANTES.md

Concluindo desafio, by: @jozemariajr.

---

content/blog/por-onde-comecar.md

- Correção de alguns erros de português
- Ênfase em nomes de variáveis fora do bloco de código

Spellcheck

---

data/links/grupos-telegram.yaml

Simplesmente ordena a lista de grupos e canais do Telegram por ordem alfabética.

Ordena lista do Telegram por ordem alfabética

---

PARTICIPANTES.md

Incluir participante André Santos da Silva

Inclusão de participante André Santos da Silva

---

PARTICIPANTES.md

Inclusão de participante: @lisboalien

---

PARTICIPANTES.md

Add participant: @dognew

---

content/desafios/d02.md
content/desafios/d03.md
content/desafios/d04.md
content/desafios/d05.md
content/desafios/d06.md
content/desafios/d07.md
content/desafios/d08.md
content/desafios/d09.md
content/desafios/d10.md
content/desafios/d11.md
content/desafios/d12.md
layouts/_default/desafio.html

Add upload instructions to all desafios.

---

PARTICIPANTES.md

-Adicionei meus dados a lista, meu user: raffaelleao

Atualização da lista de participantes.

---

content/desafios/d05.md

Incluindo endereço dos arquivos para baixar e do benchmark para o desafio 5.

Incluindo endereço dos arquivos para baixar e do benchmark para o desafio 5.

---

PARTICIPANTES.md

Inclusão de participante: @Jonhcs.

---

PARTICIPANTES.md

Inclusão de participante: @TheRealGaspar

Inclusão de participante: @TheRealGaspar

---

data/links/grupos-telegram.yaml

Olá, gostaria de adicionar meu grupo Developers na lista. Desde já agradeço!

Add grupo Developers

---

PARTICIPANTES.md

Adição do sobrenome "Andrade" ao participante "Alex Almeida".

Adição de sobrenome de participante: @alexaldr

---

PARTICIPANTES.md

Adicionei meu usuário do Github correto para o e-mail informado.

Atualizei minhas informações

---

data/links/grupos-telegram.yaml

Link já existia no arquivo. Movido para o inicio da lista como solicitado https://github.com/OsProgramadores/op-website-hugo/issues/384#issuecomment-541129897
Close #384

Resolve  #384

---

i18n/pt.yaml
layouts/partials/footer.html
static/css/style.default.css

Olá gente, 
Coloquei o grupo do telegram no footer com um icon, espero que esteja ok.

Adicionando icon do grupo no telegram no footer

---

README.md
i18n/pt.yaml
layouts/partials/footer.html

Reverts OsProgramadores/op-website-hugo#392
It does not look like the proposed change provided the needed functionality. Reverting the change.

Revert "Adicionando icon do grupo no telegram no footer"

---

config.toml
layouts/index.html
layouts/partials/see_more.html

Este PR muda o layout da página principal do site de forma a melhorar a visibilidade do botão de acesso ao grupo no Telegram.

Botao de acesso ao telegram reposicionado.

---

PARTICIPANTES.md

Inclusão de participante: @carvalhais1981.

---

PARTICIPANTES.md

Mudei meu nome de usuário a pouco tempo, ai por isso estou enviando um novo pull request com a alteração do nome antigo para o novo.

Alterando username gstfps para satuctkode

---

PARTICIPANTES.md

Inclusão de participante: @brenoferreiralima.

Inclusão de participante: @brenoferreiralima

---

PARTICIPANTES.md

Inclusão de participante: @BomfimThiago

Inclusão de participante: @BomfimThiago

---

content/blog/por-onde-comecar.md

Correção de pequeno erro de digitação.

Correção de erro de digitação no artigo por-onde-começar.

---

PARTICIPANTES.md

Hello, please check the inclusion.
ass: Arthur Alves.

Inclusão de Participante @itsArthurAlves

---

data/links/documentacao.yaml

Adicionado o GuiaFoca a seção de links do site.

Adicionado o GuiaFoca a seção de links do site.

---

data/links/cursos.yaml

Adicionados links para cursos em vídeo sobre Java, Go e Python.

Adicionados novos cursos a página de links do site.

---

content/desafios/d13.md

PR para adição do desafio 13 , seria interessante e simples adicionar um validador para o mesmo já que a saída lista os passos do cavalo no tabuleiro. O validador poderia verificar:
* Se existem 64 passos;
* Se nenhum passo se repete;
* Se o passo seguinte é formado pelo movimento do cavalo.

Add desafio 13.

---

PARTICIPANTES.md

Inclusão de participante: @MuriloAM

Inclusão de participante: @MuriloAM

---

content/blog/vetores-e-matrizes.md

Ajuste na data do artigo sobre vetores e matrizes.

Ajuste na data do artigo sobre vetores e matrizes.

---

PARTICIPANTES.md

Adicionando um novo participante conforme solicitado no Desafio #1

Participante adicionado: @ikkebr

---

PARTICIPANTES.md

Inclusão do participante Magnu Windell.

Inclusão de participante @maagwiin.

---

PARTICIPANTES.md

Pull request solicitado para completar o desafio _#1: Git Básico_ do site Os Programadores.

Inclusão de participante: @redkaio ao arquivo PARTICIPANTES.md.

---

PARTICIPANTES.md

- Re-convert the PARTICIPANTES.md file back to UTF-8 (problem
introduced by 7af6401.)

Fix the charset of PARTICIPANTES.md.

---

.travis.yml
travis/utfcheck.sh

Added UTF-8 enconding compliance check for submitted .md files.

Added UTF-8 enconding compliance check for submitted .md files.

---

PARTICIPANTES.md

Signed-off-by: Afonso Rodrigues <afonso.rodrigues@maxmilhas.com.br>
Inclusão de participante https://github.com/afonsoaugusto.

Inclusão de participante: @afonsoaugusto.

---

.github/workflows/presubmit.yaml
ci/go.mod
ci/go.sum

- Add "recursive" to also fetch submodules (hugo themes) on actions.
- Change checkparticipantes to use go modules.
- Call checkparticinates from ./ci

Also fetch submodules (hugo themes) on actions.

---

.github/workflows/presubmit.yaml

Workflow configurado para usar Go 1.15 como default.

Workflow configurado para usar Go 1.15 como default.

---

PARTICIPANTES.md

Reverts OsProgramadores/op-website-hugo#528
Decidi não participar mais do grupo, portanto prefiro não estar mais na lista de participantes.

Revert "Inclusão de participante: @isfalcantara"

---

content/desafios/d06.md

O requisito 4 do desafio comenta que:
> O formato de saída deve conter múltiplas linhas (uma por anagrama), com as **palavras ordenadas dentro de cada linha** (veja Exemplos abaixo).
Porém, o segundo exemplo não está ordenado corretamente. Por exemplo, a frase `I EGO NET` aparece em vez de `EGO I NET`. A letra E vem antes de I, logo, a linha não está ordenada.
Este pull request corrige as ordens das palavras no exemplo 2 do desafio d06.

Arruma segundo exemplo do desafio 06

---

PARTICIPANTES.md

Inclusão de participante: @apfmiranda

 No ramo desafio

---

content/desafios/d05.md

* Ajustando o número do exemplo "most_employees | Recursos Humanos" de 10 para 30.
* Para ser considerado empate, o número de funcionários deve ser o mesmo.

ajuste numero most_employees

---

PARTICIPANTES.md

Solicitação de inclusão do participante : @Thiago-Soares.

Inclusão de participante: @Thiago-Soares

---

PARTICIPANTES.md

Changes to be committed:
modified:   PARTICIPANTES.md

 On branch desafio

---

PARTICIPANTES.md

Changes to be committed: Inclusão de participante: @Daniel-Haas-B
modified:   PARTICIPANTES.md

On branch desafio

---

PARTICIPANTES.md

Adição de participante: @guiribeirodev.

Adição de participante: @guiribeirodev.

---

content/desafios/d04.md

- Na descrição do desafio já fala para não utilizar operadores condicionais. Porém como no exemplo não cita os operadores ternários, não está claro se eles são permitidos ou não.
- Ao meu ver eles não podem ser permitidos, porque são operadores condicionais e são apenas um `if-else` como notaçao diferente.

Mudar descricao do d4

---

PARTICIPANTES.md

Alterando a ordem do nome

---

content/blog/podcast-46.md

Added to Blog:
- podcast E46 - Vitor Mendrone

Added podcast E46

---

content/desafios/d06.md

Removi uma linha e alguns espaços.

Remoção de linha e de espaços

---

content/blog/podcast-47.md

Added to Blog:
- podcast E47 - André Cardoso

Added podcast E47

---

content/blog/podcast-48.md

Added to Blog:
- podcast E48 - Keit Oliveira

Added podcast E48

---

content/regras.md

Alterações na seção de regas do site.

Alterações na seção de regas do site.

---

data/links/cursos.yaml

Fixed Python para Zumbis link.

Fixed Python para Zumbis link.

---

PARTICIPANTES.md

foi incluído o participante Diogo Brito Duque na lista de participantes

inclusão do participante Diogo Brito Duque

---

data/links/cursos.yaml

Fixed broken cursos' links.

---

content/blog/podcast-49.md
content/blog/podcast-50.md

Added to Blog:
- podcast E49 - Daniela Petruzalek
- podcast E50 - Paula Santos

Added podcast E49 e E50

---

PARTICIPANTES.md

Inclusão de participante: @nrzcode.

---

content/podcasts/podcast-51.md
content/podcasts/podcast-52.md

Added to Blog:
- podcast E51 - Pachi Codes
- podcast E52 - André Carvalho

Added podcast E51 e E52

---

content/podcast/podcast-53.md
content/podcast/podcast-54.md

Added to Blog:
- podcast 53 (EN) - Nilay Yenner
- podcast E54 - Carol Valencia

Added podcasts E53 e E54

---

content/podcast/podcast-55.md
content/podcast/podcast-56.md

Added to Blog:
- podcast E55 (EN) - Matthew Miller
- podcast E56 - Paulo Brito

Added podcasts E55 - E56

---

PARTICIPANTES.md

Inclusao de participante: @ GeraldinJr.

Inclusao de participante:@ GeraldinJr.

---

PARTICIPANTES.md

Solicitando a minha inclusão como participante do grupo Os programadores.

Inclusão de participante: @DanielRosa74

---

content/podcast/podcast-57.md
content/podcast/podcast-58.md
content/podcast/podcast-59.md

Added to Blog:
podcast E57 - Daniel Maida
podcast E58 - Daniel Rosa
podcast E59 - Felipe Borges

Added podcasts 57, 58 and 59

---

PARTICIPANTES.md

Muito feliz por começar os desafios e espero aprender bastante !

Inclusão de participante: @josethiago

---

content/desafios/d01.md

Pequena alteração na instrução de commit para evitar abrir o editor padrão do git.

Mudança na instrução de commit

---

content/desafios/d01.md

Por desatenção minha, não vi que tinha mais uma ocorrência do git commit -a no item 14.4.
Esse PR é para resolver essa questão.

Alteração da segunda instrução de commit no item 14.4

---

PARTICIPANTES.md

Acabei fazendo um confusão no primeiro commit (por não ter aberto o editor e modo janela), mas consertei no segundo commit.

Desafio #1 - Git básico

---

content/podcast/podcast-60.md

Added to Blog:
- podcast E60 - Marcia Lucia Teixeira

Added podcasts E60

---

content/podcast/podcast-61.md

Added to Blog:
- podcast E61 (EN) - Kelsey Hightower

Added podcasts E61

---

data/links/cursos.yaml

Encontrei esse site meio que por acidente. Um dos contribuintes postou esse material gratuito aqui:
https://mentebinaria.gitbook.io/assembly/apendices/codigo-de-maquina
Puxando o site, ele tem cursos gratuitos de qualidade:
https://www.mentebinaria.com.br/about/
https://www.mentebinaria.com.br/treinamentos/

Adiciona Menta Binária na lista de links

---

content/podcast/podcast-62.md

Added to Blog:
- podcast E62 - Angela Bassa

Added podcasts E62

---

PARTICIPANTES.md

Realizado a Inclusão dos seguintes itens:
Nome: Anderson Santos
Nick: anderood
email: anderood@gmail.com

Inclusão de Participante: @anderood.

---

content/podcast/podcast-63.md
content/podcast/podcast-64.md

Added to Podcast:
- podcast E63 - Georges Basile
- podcast E64 - Sidney Goldbach

Added podcasts E63 - 64

---

PARTICIPANTES.md

Solicitação de inclusão de usuário.

Inclusão de participante: @Ej3r

---

content/podcast/podcast-65.md

Added to Blog:
- podcast E65 - Amanda Shafack

Added podcast E65

---

PARTICIPANTES.md

Desafio 1 incluindo participante @Zezola

Incluindo participante @Zezola

---

PARTICIPANTES.md

Inclusão das minhas informações ao PARTICIPANTES.md.

Inclusão de participante: @andretaveira90.

---

content/desafios/d13.md

- Apenas adicionando uma descrição que o parâmetro de entrada quando rodar o desafio 13, pode ser qualquer casa válida no tabuleiro. Isso não estava claro antes.

Update d13 solution description

---

data/links/cursos.yaml

Free courses addition to "Links" section:
* Git e Github para Iniciantes
* Git e Github na Vida Real
* Curso JS Moderno (ES6+)
* Aprenda NextJS, GraphQL/GraphCMS e Leaflet na prática!

Add three Willian Justen free courses on Youtube

---

PARTICIPANTES.md

Realizei a mudança do nome de usuáriona plataforma do GitHub, e fiz a atualização no arquivo PARTICIPANTES.md.

Correção do nome de usuário no link github.

---

content/desafios/d01.md

Previous tutorial was missing images.
Added links to Linux and Windows tutorials and link to official Git documentation.

Improved link to Git-related tutorials

---

PARTICIPANTES.md

Corrigindo um erro anterior. #Desafio 1

Inclusão de participante: @JGuilhermeBSB

---

content/blog/por-onde-comecar.md

Improves Por Onde Começar article.

Improves Por Onde Começar article.

---

PARTICIPANTES.md

Inclusão de participante: @devfelipelimabr

---

content/podcast/podcast-66.md
content/podcast/podcast-67.md
content/podcast/podcast-68.md
content/podcast/podcast-69.md
content/podcast/podcast-70.md
content/podcast/podcast-71.md
content/podcast/podcast-72.md
content/podcast/podcast-73.md

Adds recent podcast episodes to Podcast page

Adds recent podcast episodes to Podcast page

---

data/links/cursos.yaml
data/links/documentacao.yaml
data/links/ferramentas.yaml
data/links/podcasts.yaml
data/links/vagas.yaml

Sugestão de inclusão de 11 novas ferramentas, 3 podcasts e 2 cursos

---

data/links/telegram-grupos.yaml

- Added TypeScript BR group.
- Added NestJS BR group.

feat: new telegram groups

---

README.md

Implementacao issue #792
correcao link:
[grupo no Telegram](https://github.com/spf13/hugo/releases) --> [grupo no Telegram](https://t.me/osprogramadores).

Inclusao item "sugestao para uma boa postagem" e correcao link README.md

---

README.md
data/links/cursos.yaml

Alterando comando "hugo -wv" para "hugo server".

---

content/desafios/d08.md

```sh
$ hugo serve
Start building sites …
hugo v0.109.0+extended linux/amd64 BuildDate=unknown
| PT
-------------------+------
Pages            | 205
Paginator pages  |  30
Non-page files   |   1
Static files     | 130
Processed images |   0
Aliases          |  47
Sitemaps         |   1
Cleaned          |   0
Built in 100 ms
```

Improve d08 requirements

---

content/podcast/podcast-74.md

Adds podcast episode 74 information.

Adds podcast episode 74 information.

---

PARTICIPANTES.md

Desafio #1 Os Programadores: Git Básico.

Inclusão do participante: @bnools.

---

PARTICIPANTES.md

A IDE acabou fazendo alteração na linha #15, corrigi antes de gerar o PR para não alterar nada além do indispensável para concluir o desafio.

Desafio #01

---

PARTICIPANTES.md

Solicitação de um PR para a admissão de novo particpante.

Inclusão de participante: @soaresSilva

---

PARTICIPANTES.md

Fiz minha inclusão no repositorio.

Inclusão de participante: @JonataMSilva

---

content/desafios/d03.md

Adicionei na descrição do desafio 03 a informação dizendo que o número inicial e final devem ser incluídos nos resultados.
E também um exemplo a mais contendo os números iniciais e finais dentre os palíndromos.

Adcionando informação desafio 03

---

PARTICIPANTES.md

Novo participante, desafio 1 do site OsProgramadores.com.

Inclusão de participante: @luanhmilano.

---

content/podcast/podcast-75.md

Add Podcast Episode 75 information to site.﻿

Add Podcast Episode 75

---

content/podcast/podcast-76.md

Add Podcast Episode 76 details to site.

Add Podcast Episode 76

---

PARTICIPANTES.md

Inclusão de participante: @gabrielrbarbosa

---

content/podcast/podcast-77.md

Added podcast E77.

---

PARTICIPANTES.md

Tomei conhecimento do site através do podcast freeCodeCamp em Português com o @mpinheir . Excelente entrevista e licões de vida!
Vou tentar realizar todos os desafios em meio à minha rotina agitada! Acho que vai ser divertido! Já trabalho com desenvolvimento há algum tempo, embora não seja oriundo de nenhum curso ligado à ciência da computação. Embora me considere auto-didata, no sentido de vasculhar conteúdo e experimentar bastante, conteúdo bem curado e direto ao ponto, com boas didáticas estão sempre no meu radar, seja em Português ou majoritariamente em Inglês (felizmente ou infelizmente a maior quantidade e a melhor qualidade estarão nesse idioma).

Inclusão de participante: @disouzam

---

config.toml
layouts/partials/analytics-gtag.html
layouts/partials/head.html

Add Google Tag for Analytics.

---

content/faq.md

Modificação do artigo de FAQ para incluir sessões 
- "Por Onde Começar" 
- "Perguntar se posso perguntar"

Atualização de artigo FAQ

---

config.toml

Título autoexplicativo.
chore: disabling admin testimonials.

Desabilita a seção de Admins no site

---

content/blog/conceitos-essenciais-para-começar.md

feature: added harvard introductory computer science course link to article.

Adicionando link do vídeo de introdução a CC de Harvard

---

PARTICIPANTES.md

Inclusão de participante: @vinesdd.

---

PARTICIPANTES.md

Estou criando esse pull requeste para inclusão do Participante

Inclusão de Participante @jeanssir

---

content/desafios/d06.md

Ao iniciar a leitura do texto do desafio 06 sobre anagramas para escrever código para resolvê-lo, identifiquei um typo na palavra `anagrama` nos exemplos de chamada pela linha de comando. Duas sugestões adicionais foram feitas aproveitando essa correção inicial do typo.
1. **ae4de7b** Correção da palavra `anagrama` no texto do desafio 06 sobre Anagramas
1. **2842a86** Sugestões adicionais para maior clareza no desafio 06 - ordem alfabética mais explícita e pontuação desnecessária

Sugestões para melhoria do texto do Desafio 06 - Anagramas

---

content/blog/conceitos-essenciais-para-começar.md

feature: added freecodecamp article links to the essential conceptsarticle.
design: improved the formatting for the article

Adiciona links dos artigos da FreeCodeCamp ao artigo de conceitos essenciais

---

content/blog/portal-estagio.md

Remocão do # Projeto Portal Estágio para corrigir problema de exibição do sumário do artigo na página principal do site

Corrige problema de exibição no artigo portal estagio

---

content/blog/ola-mundo.md

Mudei o nome do artigo por onde começar e reforcei a importância de ler o artigo de conceitos essenciais

Renomeia artigo por onde começar

---

content/blog/inteligencia-artificial.md

Achei que era hora de colocar um artigo sobre inteligência artificial no stie.

Adiciona artigo sobre Inteligência Artificial.

---

content/blog/conceitos-essenciais-para-começar.md

Corrige link quebrado

---

content/blog/conceitos-essenciais-para-começar.md

Atualiza titulo do artigo por onde começar.

Atualiza titulo do artigo por onde começar.

---

PARTICIPANTES.md

Nova tentativa, favor validarem o PR.

Criação do arquivo PARTICIPANTES.md

---

content/blog/conceitos-essenciais-para-começar.md

- corrige os links quebrados no artigo
- passa a usar pathing relativo nos links internos

Pequenas correções no artigo de conceitos essenciais

---

content/blog/contrib-odin.md

fix: corrige o link quebrado para as Goroutines

Corrição do link quebrado para as Goroutines no artigo do Lucas

---

content/podcast/podcast-81.md

feature: adiciona o episódio 81 ao catálogo de podcasts do site.

Podcast: Adiciona o episódio 81 ao catálogo do site.

---

PARTICIPANTES.md

Adicionado meu nome a lista de participantes para conclusão do desafio 0.

Adicionado meu nome e usuário do git a lista de participantes.

---

content/podcast/podcast-82.md

feature: adiciona o ep 82 do podcast ao catálogo.

Adiciona o episódio 82 ao catálogo do site

---

content/blog/tiktok-canal.md
content/faq.md

Foram feitas as seguintes adições:
1. Adicionado sessão de Podcast no FAQ, contendo os links para o Youtube, Spotify e Tiktok
2. Adicionado blogpost informando sobre o canal do Tiktok.

Adicionando o Tiktok ao site

---

content/podcast/podcast-83.md

Adiciona o EP 83 ao catálogo do site.
Está comentado o player do Spotify para quando for publicado o áudio também.

Adiciona o episódio 83 ao catálogo do site.

---

content/podcast/podcast-83.md
content/podcast/podcast-84.md

Adiciona o episódio 84 ao catálogo do site.
Notas:
Player embedded habilitado
Player do spotify temporariamente indisponível

Adição do EP 84 ao catálogo do site

---

PARTICIPANTES.md

Estou iniciando os desafios propostos no site.

Inclusão de participante: @luanzanetich

---

content/blog/conceitos-essenciais-para-começar.md
content/podcast/podcast-81.md
content/podcast/podcast-82.md
content/podcast/podcast-84.md

- Adiciona player embedded do YouTube ao episódio 81
- Adiciona player embedded do YouTube ao episódio 82
- Adiciona player embedded do Spotify ao episódio 84
- Remove um ')' extra no artigo de conceitos essenciais

Pequenos ajustes - Podcasts 81, 82 e 84 + Correção de texto em artigo

---

content/podcast/podcast-85.md

Adiciona o episódio 85 ao catálogo do site com o player do YouTube.

Adiciona episódio 85 ao catálogo

---

PARTICIPANTES.md

Adicionar minhas informações a lista de participantes do desafio

Inclusão de participante: @luan-dantas

---

content/podcast/podcast-85.md
content/podcast/podcast-86.md

Adiciona o player embedded do spotify aos episódios 85 e 86 do podcast.
Corrige a URL do player do youtube do episódio 86.

Adiciona os players do Spotify aos episódios 85 e 86 do Podcast

---

PARTICIPANTES.md

Inclusão de Participante

---

PARTICIPANTES.md

Pull request para minha inclusão como participante nos desafios do grupo 'Os Programadores'.

Inclusão de participante: @AlexPHorta.

---

PARTICIPANTES.md

Solicito inclusão do meu nome como participante.

Inclusão de participante: @sergioherman.

---

PARTICIPANTES.md

Solicito a inclusão do meu nome e dados como novo participante do desafio.

Inclusão de participante @Miguel-V-DF

---

content/podcast/podcast-87.md
content/podcast/podcast-88.md

Adiciona o Episódio 88 ao catálogo do site.
Atualiza a página do episódio 87 para adicionar o player do Spotify e a descrição mais detalhada que estava na página do Spotify.

Atualização do Catálogo dos Podcasts

---

PARTICIPANTES.md

Adição do participante Alison atrasada 😩

add participant @imalisoon | Alison

---

data/links/ferramentas.yaml

Adição dos links ime.usp.br/~pf/ e Wikiversity

---

PARTICIPANTES.md

desafio 1 de osprogramadores, add do participante joseildoandrade12

Inclusão de participante: @joseildoandrade12

---

content/podcast/podcast-90.md

Adiciona ep 90 do podcast ao catalogo do site sem o player do spotify.

Podcast - Adiciona episodio 90

---

PARTICIPANTES.md

Inclusão de participante: @strelogg. Tentativa N°4.

---

content/podcast/podcast-91.md

**Pendência**: Incluir o endereço do episódio no Spotify na página

Adicionar EP.91 do podcast ao catalogo

---

PARTICIPANTES.md

Mudei meu nome de usuário do Github e atualizei aqui.

Desafio - Mudança de Nome

---

content/podcast/podcast-92.md

feat:ep92 - Add Spotify Link

---

content/blog/conceitos-essenciais.md

Atualizei o link para o artigo da IFBA usando o Web Archive, nele tem a última screenshot da página antes de dar o erro 404.

Atualização do link para o artigo da IFBA - Blog: Conceitos Essenciais

---

content/podcast/podcast-93.md

Feat(EP.93) - Add Episode

---

content/blog/conceitos-essenciais.md
content/blog/git-reset.md
content/blog/ola-mundo.md
content/blog/pensando-como-um-programador.md

Adiciona a categoria _iniciantes_ nos artigos para facilitar que os novatos encontrem artigos focado neles.
Feature: adiciona a categoria "iniciantes" nos artigos.
fix: corrige a categoria "desafios" no artigo de conceitos iniciais

Adiciona categoria "iniciantes" nos artigos

---

content/podcast/podcast-94.md

(feat) Add episode 94

---

content/podcast/podcast-95.md

(feat) Add episode 95 in podcasts

---

PARTICIPANTES.md

Inclui o participante Marcus Wendell @mwendellsmce no arquivo PARTICIPANTES.md.

Inclusão do participante: @mwendellsmce.

---

PARTICIPANTES.md

Inclusão de participante no desafio 1

Inclusão de participante: @GutierreArruda

---

content/podcast/podcast-95.md

Adiciona link do spotify ao ep-95

---

content/podcast/podcast-96.md

Add Ep-96 in podcast

---

content/podcast/podcast-96.md

Adiciona link do spotify ao ep-96

---

PARTICIPANTES.md
README.md

Boa tarde, solicito inclusão de participante ao projeto. 
Jessica Macedo Rafael 
jessica.crei@gmail.com

Inclusão de participante: @jessicamacedorafael

---

content/podcast/podcast-97.md

feat: Adiciona episódio 97 ao catálogo de podcast

---

PARTICIPANTES.md

PR com a alteração do desafio #1.

Inclusão de participante: @leohiroshi

---

content/podcast/podcast-89.md
content/podcast/podcast-90.md
content/podcast/podcast-91.md
content/podcast/podcast-92.md
content/podcast/podcast-93.md
content/podcast/podcast-94.md
content/podcast/podcast-95.md
content/podcast/podcast-96.md
content/podcast/podcast-97.md

chore: ajuste da linha que convida ao grupo para adicionar hiperlink do telegram

Correção do texto para o grupo - Episódios 88 ao 97

---

content/podcast/podcast-97.md
content/podcast/podcast-98.md

1. Adiciona o player de áudio (spotify) do episódio 97
2. Adiciona o episódio 98 ao catálogo do site

Atualização Catálogo do Podcast

---

PARTICIPANTES.md

Inclusão do novo participante, @frankdantas

Inclusão de participante: @frankdantas

---

content/podcast/podcast-100.md
content/podcast/podcast-99.md

Add Ep 99 & 100

---

PARTICIPANTES.md

Inclusão dos meus dados no arquivo de participantes.

Inclusão de participante: @alexandrevarga.

---

PARTICIPANTES.md

Inserção de Participante: Th3Progr4mm3r

Inclusão de participante: @Th3Progr4mm3r

---

content/podcast/podcast-103.md

Feat: add episode 103 in podcast

---

content/podcast/podcast-104.md

Feat: Add ep-104 in podcast

---

content/podcast/podcast-105.md

feat: Add episode 105 in podcast

---

data/links/ferramentas.yaml

4Devs adicionado na lista de links, em Ferramentas

Link com diversas ferramentas para programadores.

---

data/links/ferramentas.yaml

Quick Reference adicionado na lista de links, em Ferramentas

Exemplos de códigos, ferramentas e comandos para consulta.

---

content/podcast/podcast-112.md
content/podcast/podcast-113.md
content/podcast/podcast-114.md

feat(podcast): adiciona episódios 112, 113 e 114
